/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.infusionsoft.api;

import com.infusionsoft.ApiException;
import com.infusionsoft.model.InfusionsoftAccountProfile;
import com.infusionsoft.model.InfusionsoftError;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountInfoApi
 */
@Ignore
public class AccountInfoApiTest {

    private final AccountInfoApi api = new AccountInfoApi();

    
    /**
     * Retrieve account profile
     *
     * Retrieves profile/company info for an account.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountProfileUsingGETTest() throws ApiException {
        InfusionsoftAccountProfile response = api.getAccountProfileUsingGET();

        // TODO: test validations
    }
    
}
