/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.infusionsoft.api;

import com.infusionsoft.ApiException;
import com.infusionsoft.model.InfusionsoftError;
import com.infusionsoft.model.InfusionsoftProduct;
import com.infusionsoft.model.InfusionsoftProductList;
import com.infusionsoft.model.InfusionsoftProductStatusList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductApi
 */
@Ignore
public class ProductApiTest {

    private final ProductApi api = new ProductApi();

    
    /**
     * Retrieve a Product
     *
     * Retrieves a single product from the authorized Infusionsoft account
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProductUsingGETTest() throws ApiException {
        Long productId = null;
        InfusionsoftProduct response = api.getProductUsingGET(productId);

        // TODO: test validations
    }
    
    /**
     * Retrieve Synced Products
     *
     * The Sync endpoint returns a set of products that have been updated or created since the last result set was retrieved, minus any products that have been deleted.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listProductsFromSyncTokenUsingGETTest() throws ApiException {
        String syncToken = null;
        Integer limit = null;
        Integer offset = null;
        InfusionsoftProductStatusList response = api.listProductsFromSyncTokenUsingGET(syncToken, limit, offset);

        // TODO: test validations
    }
    
    /**
     * List Products
     *
     * Retrieves a list of all products
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listProductsUsingGETTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        Boolean active = null;
        InfusionsoftProductList response = api.listProductsUsingGET(limit, offset, active);

        // TODO: test validations
    }
    
}
