/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.70.0.156820
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.infusionsoft.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;

/**
 * InfusionsoftInvoicePayment
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-12T23:10:31.052Z")
public class InfusionsoftInvoicePayment {
  @SerializedName("amount")
  private BigDecimal amount = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("invoice_id")
  private Long invoiceId = null;

  @SerializedName("last_updated")
  private OffsetDateTime lastUpdated = null;

  @SerializedName("note")
  private String note = null;

  @SerializedName("pay_date")
  private OffsetDateTime payDate = null;

  @SerializedName("pay_status")
  private String payStatus = null;

  @SerializedName("payment_id")
  private Long paymentId = null;

  @SerializedName("refund_invoice_payment_id")
  private Long refundInvoicePaymentId = null;

  @SerializedName("skip_commission")
  private Boolean skipCommission = null;

  public InfusionsoftInvoicePayment amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public InfusionsoftInvoicePayment id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public InfusionsoftInvoicePayment invoiceId(Long invoiceId) {
    this.invoiceId = invoiceId;
    return this;
  }

   /**
   * Get invoiceId
   * @return invoiceId
  **/
  @ApiModelProperty(value = "")
  public Long getInvoiceId() {
    return invoiceId;
  }

  public void setInvoiceId(Long invoiceId) {
    this.invoiceId = invoiceId;
  }

  public InfusionsoftInvoicePayment lastUpdated(OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
    return this;
  }

   /**
   * Get lastUpdated
   * @return lastUpdated
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }

  public void setLastUpdated(OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
  }

  public InfusionsoftInvoicePayment note(String note) {
    this.note = note;
    return this;
  }

   /**
   * Get note
   * @return note
  **/
  @ApiModelProperty(value = "")
  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }

  public InfusionsoftInvoicePayment payDate(OffsetDateTime payDate) {
    this.payDate = payDate;
    return this;
  }

   /**
   * Get payDate
   * @return payDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getPayDate() {
    return payDate;
  }

  public void setPayDate(OffsetDateTime payDate) {
    this.payDate = payDate;
  }

  public InfusionsoftInvoicePayment payStatus(String payStatus) {
    this.payStatus = payStatus;
    return this;
  }

   /**
   * Get payStatus
   * @return payStatus
  **/
  @ApiModelProperty(value = "")
  public String getPayStatus() {
    return payStatus;
  }

  public void setPayStatus(String payStatus) {
    this.payStatus = payStatus;
  }

  public InfusionsoftInvoicePayment paymentId(Long paymentId) {
    this.paymentId = paymentId;
    return this;
  }

   /**
   * Get paymentId
   * @return paymentId
  **/
  @ApiModelProperty(value = "")
  public Long getPaymentId() {
    return paymentId;
  }

  public void setPaymentId(Long paymentId) {
    this.paymentId = paymentId;
  }

  public InfusionsoftInvoicePayment refundInvoicePaymentId(Long refundInvoicePaymentId) {
    this.refundInvoicePaymentId = refundInvoicePaymentId;
    return this;
  }

   /**
   * Get refundInvoicePaymentId
   * @return refundInvoicePaymentId
  **/
  @ApiModelProperty(value = "")
  public Long getRefundInvoicePaymentId() {
    return refundInvoicePaymentId;
  }

  public void setRefundInvoicePaymentId(Long refundInvoicePaymentId) {
    this.refundInvoicePaymentId = refundInvoicePaymentId;
  }

  public InfusionsoftInvoicePayment skipCommission(Boolean skipCommission) {
    this.skipCommission = skipCommission;
    return this;
  }

   /**
   * Get skipCommission
   * @return skipCommission
  **/
  @ApiModelProperty(value = "")
  public Boolean isSkipCommission() {
    return skipCommission;
  }

  public void setSkipCommission(Boolean skipCommission) {
    this.skipCommission = skipCommission;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InfusionsoftInvoicePayment invoicePayment = (InfusionsoftInvoicePayment) o;
    return Objects.equals(this.amount, invoicePayment.amount) &&
        Objects.equals(this.id, invoicePayment.id) &&
        Objects.equals(this.invoiceId, invoicePayment.invoiceId) &&
        Objects.equals(this.lastUpdated, invoicePayment.lastUpdated) &&
        Objects.equals(this.note, invoicePayment.note) &&
        Objects.equals(this.payDate, invoicePayment.payDate) &&
        Objects.equals(this.payStatus, invoicePayment.payStatus) &&
        Objects.equals(this.paymentId, invoicePayment.paymentId) &&
        Objects.equals(this.refundInvoicePaymentId, invoicePayment.refundInvoicePaymentId) &&
        Objects.equals(this.skipCommission, invoicePayment.skipCommission);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, id, invoiceId, lastUpdated, note, payDate, payStatus, paymentId, refundInvoicePaymentId, skipCommission);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InfusionsoftInvoicePayment {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    invoiceId: ").append(toIndentedString(invoiceId)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    payDate: ").append(toIndentedString(payDate)).append("\n");
    sb.append("    payStatus: ").append(toIndentedString(payStatus)).append("\n");
    sb.append("    paymentId: ").append(toIndentedString(paymentId)).append("\n");
    sb.append("    refundInvoicePaymentId: ").append(toIndentedString(refundInvoicePaymentId)).append("\n");
    sb.append("    skipCommission: ").append(toIndentedString(skipCommission)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

